name: azure.governance.publishrelease$(Rev:.r)

trigger:
  batch: "true"
  branches:
    include:
      - release/*
  paths:
    include:
      - src/terraform

pr: none

variables:
  - name: TF_INPUT
    value: "false"
  - name: TF_IN_AUTOMATION
    value: "true"
  - name: TF_VERSION
    value: 0.12.19

stages:
  - stage: publishRelease

    jobs:
      - job: publishArtifacts
        displayName: Publish Azure Governance Terraform files/plans.

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - publish: src/terraform
            displayName: "Release Azure Governance."
            artifact: releaseAzureGovernance
            enabled: "true"

      - job: publishDevPlan
        displayName: Publish dev plan
        variables:
          - group: azuregovernancedev
          - group: azuregovernancedevsecret
        pool:
          vmImage: "ubuntu-latest"
        container:
          image: rjfmachado.azurecr.io/terraform:${{ variables['TF_VERSION'] }}
          endpoint: rjfmachado.containers
        steps:
          - template: /pipelines/templates/tf-init-plan.yaml
            parameters:
              tfDir: src/terraform
              tfCliInit: -backend=true -backend-config=dev.stage
              tfCliPlan: -out dev.plan -var-file=dev.tfvars.json

          - publish: src/terraform/dev.plan
            displayName: "Publish Dev Plan"
            artifact: releaseAzureGovernance.devplan
            enabled: "true"

      - job: publishProdPlan
        displayName: Publish prod plan
        variables:
          - group: azuregovernanceprod
          - group: azuregovernanceprodsecret
        pool:
          vmImage: "ubuntu-latest"
        container:
          image: rjfmachado.azurecr.io/terraform:${{ variables['TF_VERSION'] }}
          endpoint: rjfmachado.containers
        steps:
          - template: /pipelines/templates/tf-init-plan.yaml
            parameters:
              tfDir: src/terraform
              tfCliInit: -backend=true -backend-config=prod.stage
              tfCliPlan: -out prod.plan  -var-file=prod.tfvars.json

          - publish: src/terraform/prod.plan
            displayName: "Publish Prod Plan"
            artifact: releaseAzureGovernance.prodplan
            enabled: "true"
